services:
  app:
    container_name: smart-shell-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: $API_URL
        API_SUNAT_TOKEN: $API_SUNAT_TOKEN
    environment:
        API_URL: $API_URL
        API_SUNAT_TOKEN: $API_SUNAT_TOKEN
    ports:
      - "${SMART_SHELL_ANGULAR_PORT}:4201"
    networks:
      - smart-shell-net
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true
