services:
  smart-shell-angular:
    container_name: smart-shell-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: $API_URL
        API_SUNAT_TOKEN: $API_SUNAT_TOKEN
    environment:
        API_URL: $API_URL
        API_SUNAT_TOKEN: $API_SUNAT_TOKEN
    ports:
      - "4200:4200"

networks:
  smart-shell-net:
    external: true
